language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python run.py

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: cache
  on:
    branch: master